sekwah41/Advanced-Portals

src/com/sekwah/advancedportals/AdvancedPortalsCommand.java

Hi,
it was frustrating that "/portal portal" didn't give a portal block cause it doesn't exist.
This makes the help message less confusing 😄

Fix portal block command in help message

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/PluginMessageReceiver.java
src/main/java/com/sekwah/advancedportals/bungee/listener/PluginMessageReceiver.java

When using this plugin, there was an issue where the first connected user did not warp to the desired location. So I thought of a delay for 20 ticks, which actually worked. This seems to be an issue because first-time users go through more steps than previously connected users.
And I added logic to check if the user information coming into the PluginMessageChannel is actually the user connected to the server. When I tried to connect to the server and tweaked it, I checked that an error occurred because the null check did not work properly.

[Emergency] bukkit PluginMessageReceiver add null-check/delay 20Ticks

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java

Added else if statement at line 80 checking for single arg instead of 2. This should now only appear if a player both has permission and has not specified a portal to warp to.

Fixed issue where help menu appears on successful warp

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/PluginMessageReceiver.java

Warp player when PluginMessage arrives if the player has already joined. Otherwise cache the data from the PluginMessage and handle the warp during PlayerJoinEvent.

Fix timing issues with bungeecord destination warps

---

src/main/resources/plugin.yml

Luckperms tries to hide commands you dont have access to. But this works only if the permissions for the commands were set in plugin.yml.
Before:
After:

Command permissions for luckperms

---

build.gradle

📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.6.0--canary.263.03a8363</code>

chore(ci): Update version-bumping task order

---

.github/PULL_REQUEST_TEMPLATE/pr_changelog_release_notes.md
src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java

There were a few commands in the tab complete missing not in the latest version.

feat: Added missing commands from tab complete

---

src/main/resources/plugin.yml

The issue is with the current perm its both for the internal command code and spigot's system. So you get too much access.
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.7.0--canary.275.895fcc6</code>

fix: Access to portal warp command locked behind wrong perm

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java

Fixes the issue where in survival mode sometimes nether portals will move you to the nether rather than the proper destination.
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.7.1--canary.280.34b57bb</code>

fix: Issue where portal events activate too early in survival

---

build.gradle
src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java
src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
src/main/java/com/sekwah/advancedportals/bukkit/Settings.java
src/main/java/com/sekwah/advancedportals/bukkit/config/ConfigHelper.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
src/main/java/com/sekwah/advancedportals/bukkit/util/WorldEditIntegration.java
src/main/resources/config.yml
src/main/resources/plugin.yml

As mentioned here, you're fine with a WorldEdit integration.
https://github.com/sekwah41/Advanced-Portals/issues/44
And I want to add it in this PR.
I really like AdvancedPortals but too many wands are terrible. I added a config option to enable WorldEdit integration.
With that option:
- AdvancedPortals uses the WorldEdit selections (has to be a cuboid selection, uses the same player world. This is a limitation but imo it's not that big problem. 
- Disable /portal wand and /portal selector when WorldEdit integration is active
When WorldEdit is installed:
- Add /portal we-selection <name> to select the portal as worldedit selection
WorldEdit is marked as soft-depend, you don't need to install worldedit for AdvancedPortals.

Add WorldEdit integration to AdvancedPortals

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java

Fix the bug introduced with the world edit integration making portals unable to be created without using world edit.

fix: Error in position checks for portal creation

---

src/main/java/com/sekwah/advancedportals/velocity/AdvancedPortalsPlugin.java
src/main/resources/bungee.yml
src/main/resources/plugin.yml

Fixes #334 and fixes #326
Name was changed to the one on spigotmc.org to allow easier detection by autoplug.
I couldnt find a velocity-plugin.json file in the repo, guess it gets auto-generated via the `@Plugin` annotation.

Updated author name, fixes #334 and #326

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java

For my use case, I need to be able to reload the portal config from the console and/or rcon.  However that doesn't work:
```
[17:08:29 INFO]: [AdvancedPortals] You cannot use commands with the console.
```
This small change in the command handler addresses this specific issue.
I'm not sure why this restriction is in place, but this results in the behavior I need...

make "portal reload" command usable from the console and rcon

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java

fix: Add Selector Alias (Wand) in Help Message
Changes message to include alias as well
Closes
#333

fix: Add Selector Alias (Wand) in Help Message

---

core/src/main/java/com/sekwah/advancedportals/core/tags/activation/PermissionTag.java
lang/src/main/resources/lang/en_GB.lang

Fix: Permission Tag

---

build.gradle
bungee/build.gradle
core/build.gradle
spigot/build.gradle

Use updated methods.
Update dependencies

Gradle Reduction

---

core/src/main/java/com/sekwah/advancedportals/core/commands/CommandWithSubCommands.java

So the list that is being filtered is immutable, hence doesn't work with in conjunction with removeIf.
There are two solutions, either
- stream it (which I've done in this PR since I believe it to be more efficient)
OR
- create a new ArrayList each time for filtering since that is mutable
```[13:00:27 ERROR]: Exception when FlippinDuckMan attempted to tab complete advancedportals create name:test3 command:"d
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/advancedportals create name:test3 command:"d' in plugin AdvancedPortals v1.0.0
at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[PaperCrane-API-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.Command.tabComplete(Command.java:93) …
```

fix: autocomplete strings come up with error.

---

src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
src/main/java/com/sekwah/advancedportals/bukkit/PluginMessages.java
src/main/java/com/sekwah/advancedportals/bukkit/destinations/Destination.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
src/main/java/com/sekwah/advancedportals/bukkit/listeners/PortalProtect.java
src/main/java/com/sekwah/advancedportals/bukkit/portals/Portal.java
src/main/resources/config.yml
src/main/resources/messages.yml

feat: add custom messages to several options:
1. Join Cooldown Protection
2. No Portal Permission
3. No Portal Cooldown
This is all moved to a new configuration file called messages.yml so that config.yml doesn't become convoluted (Including the move of prefix and warp message)
Fixes
#144
#224

feat: add custom messages to plugin

---

src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java

Checks if player has `HAS_WARPED` metadata when joining a server (shouldn't have it when logging/joining a server anyway) and removes it if they do. 
Alternatively it could be put in the `PlayerQuitEvent` but I don't think it should be fine for the `PlayerJoinEvent`.
Was tested in a live environment by @RillSoji
Fixes #329

FIX: Remove HAS_WARPED Metadata when logging into a new server

---

CHANGELOG.md
build.gradle
changelog-util.gradle
discord.gradle
gradle.properties
settings.gradle

chore: release files extra fixes

---

lang/src/main/resources/lang/en_GB.lang
spigot/build.gradle
spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java
spigot/src/main/java/com/sekwah/advancedportals/spigot/tags/ConditionsTag.java
spigot/src/main/templates/plugin.yml

Allows admins to select specific clauses for when a portal can be used / not be used.
#434 is related, although it can be done better.

feat: add placeholder api conditions support

---

.github/workflows/release-please.yml
.github/workflows/snapshots.yml

As the main module needs java 8, might as well allow better support for back in 1.12 and such for lower java versions

fix: lower java requirement to 8 for spigot builds

---

spigot/src/main/java/com/sekwah/advancedportals/spigot/Listeners.java

fixes #533 
This optimized version using streams is more efficient than the latter one because it avoids creating an intermediate array and processes each BlockState directly as it is filtered. This reduces memory overhead and can improve performance, especially when dealing with large collections.

fix: rework onChunkLoad
