- src/com/sekwah/advancedportals/listeners/PortalProtect.java
Added error message when players don't have build permission as per #94 .
[Screenshot of code test.](https://xorg.us/uGppjh.png)
> Added error message when players don't have build permission.

- Resources/lang/hu_HU.lang
I do not know if it can be translated, but I do not know if only one file is translated.
Fixes: []
Tweaks: []
I've also translated the "#" mark.
> Added hungarian (hu_HU.lang) translation file

- src/com/sekwah/advancedportals/AdvancedPortalsCommand.java
Tweaks:
- Added `warp` subcommand to command `/portal`.
> Add command to warp to portal.

- build.gradle
- src/main/java/com/sekwah/advancedportals/AdvancedPortalsCommand.java
- src/main/java/com/sekwah/advancedportals/listeners/Listeners.java
- src/main/resources/plugin.yml
As title says, get on reviewing it Rezel ;)
> Fix for wand command

- src/main/resources/lang/de_DE
I hope this file support UTF 8 because äöü.
> Add German Translation

- README.md
- src/main/java/com/sekwah/advancedportals/AdvancedPortalsCommand.java
- src/main/java/com/sekwah/advancedportals/AdvancedPortalsPlugin.java
- src/main/java/com/sekwah/advancedportals/PluginMessages.java
- src/main/java/com/sekwah/advancedportals/destinations/Destination.java
- src/main/java/com/sekwah/advancedportals/metrics/Metrics.java
- src/main/java/com/sekwah/advancedportals/portals/Portal.java
- src/main/resources/plugin.yml
Also updated the colour code conversion
> Added message tag

- src/main/java/com/sekwah/advancedportals/portals/Portal.java
Add ''to enter this portal'' instead of ''to teleport to (loc)"
Change seconds to second(s)
> Update Portal.java and make text more clear

- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java
- src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java
- src/main/java/com/sekwah/advancedportals/bukkit/portals/AdvancedPortal.java
- src/main/java/com/sekwah/advancedportals/bukkit/portals/Portal.java
Implemented #184
**Builds succesfully**,
**Tested:** On my local server 1.15.2
**"Breaking" changes:** 
- Changed `AdvancedPortal` ctor,
- Changed `Portal.cooldown` type,
- PortalCooldown config value is not used anymore,
- breaks events - onTeleportEvent, onWorldChangeEvent, onJoinEvent
> Add cooldown per portal feature

- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
For some custom forks like Tuinity and such.
Also this next warning is enormous and just annoying. I think there's should be some configurable option in the config to disable it. Can make a PR for this too if needed.
> better check for bungeecord support

- src/main/java/com/sekwah/advancedportals/bungee/listener/EventListener.java
- src/main/java/com/sekwah/advancedportals/bungee/listener/PluginMessageReceiver.java
Uses the `ServerConnectedEvent` instead of `ServerSwitchEvent` and removed the timed delay.
> Use ServerConnectedEvent for bungee relay

- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsCommand.java
- src/main/java/com/sekwah/advancedportals/bukkit/destinations/Destination.java
- src/main/java/com/sekwah/advancedportals/bukkit/effects/WarpEffects.java
- src/main/java/com/sekwah/advancedportals/bukkit/portals/Portal.java
Added new two new variables:
- `particledisp` - particles at the point of dispatch 
- `particledest` - particles at the point of destination
Both variables accepts particle name from: [https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html#enum.constant.summary](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html#enum.constant.summary)
Tested cores:
- spigot 1.13.2
- spigot 1.14.4
- spigot 1.15.2
- paper 1.16.5
Result example:
> Custom warp effects via particles

- .github/workflows/gradle.yml
- CHANGELOG.md
- build.gradle
- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
- src/main/java/com/sekwah/advancedportals/velocity/AdvancedPortalsPlugin.java
As the title suggests. More info can be found in the changelog.
> Add force enable features and proper velocity support

- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
- src/main/java/com/sekwah/advancedportals/bukkit/config/ConfigHelper.java
- src/main/resources/config.yml
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.7.2--canary.292.26e78ff</code>
> feat: Allow the ability to disable the proxy warning message

- src/main/java/com/sekwah/advancedportals/bukkit/PluginMessages.java
- src/main/java/com/sekwah/advancedportals/bukkit/destinations/Destination.java
- src/main/resources/config.yml
fixes: #299 
Added support to configure the warp message, including a default fallback to the existing one.
> feat: Adds ability to configure warp message

- docs/worldedit.md
Documentation changes for
https://github.com/sekwah41/Advanced-Portals/pull/307
I only added the worldedit.md, I'm not familiar with the website development.
You should add a weblink or smth else to display it.
> feat: WorldEdit Integration: add README

- src/main/java/com/sekwah/advancedportals/bukkit/portals/Portal.java
Fixes #300
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.9.1--canary.318.672b544</code>
> fix: Removes the false positive warning from McAntiMalware

- build.gradle
- src/main/java/com/sekwah/advancedportals/bukkit/AdvancedPortalsPlugin.java
> Fix proxy detection

- README.md
📦 Published PR to [discord](https://discord.sekwah.com/) as canary version: <code>0.9.2-canary.344.a9e83f0-SNAPSHOT</code>
> chore: small readme change to force an update

- README.md
Follow up to #368. Some links were broken.
> Point to documentation in README

- docs/intro.md
I threw together a simple written tutorial that covers the basics of portal creation. Let me know if it looks good.
Thanks for the plugin, it's quite nice and easy to use.
> Add written tutorial

- src/main/java/com/sekwah/advancedportals/velocity/AdvancedPortalsPlugin.java
fix: missing author in velocity plugin
Unsure if something needs to be added to the autoupdate thing you have going.
Closes
#374
> fix: add author for velocity plugin

- src/main/java/com/sekwah/advancedportals/bukkit/api/warphandler/TagHandler.java
> style: Fix Typo

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/permissions/PortalPermissions.java
- core/src/main/java/com/sekwah/advancedportals/core/portal/AdvancedPortal.java
- core/src/main/java/com/sekwah/advancedportals/core/serializeddata/DataStorage.java
- core/src/main/java/com/sekwah/advancedportals/core/services/PortalServices.java
- core/src/main/java/com/sekwah/advancedportals/core/tags/activation/NameTag.java
- core/src/main/java/com/sekwah/advancedportals/core/tags/activation/PermissionTag.java
- core/src/main/java/com/sekwah/advancedportals/core/warphandler/Tag.java
- lang/src/main/resources/lang/en_GB.lang
- spigot/src/main/java/com/sekwah/advancedportals/spigot/connector/container/SpigotServerContainer.java
- Fix error in folder creation.
- Use output file directly instead of asserting a new one
> Recode Updates

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/commands/subcommands/desti/CreateDestiSubCommand.java
- core/src/main/java/com/sekwah/advancedportals/core/commands/subcommands/desti/TeleportDestiSubCommand.java
- core/src/main/java/com/sekwah/advancedportals/core/permissions/PortalPermissions.java
- core/src/main/java/com/sekwah/advancedportals/core/services/DestinationServices.java
- lang/src/main/resources/lang/en_GB.lang
- Also fixes typo and copy pasta in other destination subcommands. 
- Also adds a desti permission in permission registry
> Feat: Add destination teleport subcommand

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/CoreListeners.java
- core/src/main/java/com/sekwah/advancedportals/core/connector/containers/ServerContainer.java
- core/src/main/java/com/sekwah/advancedportals/core/tags/BungeeTag.java
- core/src/main/java/com/sekwah/advancedportals/core/tags/MessageTag.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/commands/subcommands/portal/ImportPortalSubCommand.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/connector/container/SpigotServerContainer.java
New behavior is being properly split out as bungee tags and proxy tags.
This implementation is just for the "Connect" packet bungee supports.
> feat: bungee tags

- .github/workflows/pre-commit-check.yaml
> chore: update readme

- .github/workflows/release-please.yml
> chore: switch to using env

- build.gradle
- gradle.properties
> fix: version number is now set correctly, was 1.0.0

- core/src/main/java/com/sekwah/advancedportals/core/repository/ConfigRepository.java
- core/src/main/java/com/sekwah/advancedportals/core/repository/impl/ConfigRepositoryImpl.java
- core/src/main/java/com/sekwah/advancedportals/core/serializeddata/config/Config.java
- core/src/main/java/com/sekwah/advancedportals/core/services/PortalServices.java
> fix: disable spectators triggering portals by default

- core/src/main/java/com/sekwah/advancedportals/core/repository/ConfigRepository.java
- core/src/main/java/com/sekwah/advancedportals/core/repository/impl/ConfigRepositoryImpl.java
- lang/src/main/resources/lang/en_GB.lang
- spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/commands/subcommands/portal/ImportPortalSubCommand.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/importer/LegacyImporter.java
> config-import

- spigot/src/main/java/com/sekwah/advancedportals/spigot/Listeners.java
> fix: NullPointerExceptions

- core/src/main/java/com/sekwah/advancedportals/core/serializeddata/DataStorage.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java
> fix: comment out log spam

- core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java
- core/src/main/java/com/sekwah/advancedportals/core/util/TagReader.java
- spigot/build.gradle
> Small fix plus maven

- core/src/main/java/com/sekwah/advancedportals/core/services/DestinationServices.java
- lang/src/main/resources/lang/en_GB.lang
> fix: check for world existence

- core/src/main/java/com/sekwah/advancedportals/core/services/DestinationServices.java
- core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java
- lang/src/main/resources/lang/en_GB.lang
> fix: teleport call that doesn't check world

- build.gradle
- legacyspigot/build.gradle
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/AdvancedPortalsPlugin.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/LegacySpigotInfoLogger.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/Listeners.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/PermissionsGeneratorSpigot.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/commands/subcommands/portal/ImportPortalSubCommand.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/command/LegacySpigotCommandHandler.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/command/LegacySpigotCommandRegister.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotCommandSenderContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotEntityContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotPlayerContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotServerContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotWorldContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/importer/ConfigAccessor.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/importer/LegacyImporter.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/metrics/Metrics.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/tags/ConditionsTag.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/utils/ContainerHelpers.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/warpeffects/EnderWarpEffect.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/warpeffects/SpigotWarpEffects.java
- legacyspigot/src/main/templates/plugin.yml
- settings.gradle
Will need some build fixes and testing.
#514
> feat: legacy plugin

- .github/workflows/release-please.yml
- .github/workflows/snapshots.yml
> chore: cleanup workflow indentation

- spigot/src/main/java/com/sekwah/advancedportals/spigot/Listeners.java
> fix: add null checks

- lang/src/main/resources/lang/pt-br.yml
> Add new language PT-BR Português Brasil

- build.gradle
- lang/src/main/resources/lang/en_GB.lang
- spigot/build.gradle
- spigot/src/main/java/com/sekwah/advancedportals/spigot/AdvancedPortalsPlugin.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/tags/CostTag.java
- spigot/src/main/templates/plugin.yml
Hooks into essentials economy and takes money from the account of the player if the player has the certain amount of money to enter the portal.
> feat: tag cost

- .devcontainer/devcontainer.json
- README.md
Update the `README.md` file to include new sections and update the contributing guidelines.
* **Environment Configuration**: Add a new section explaining the use of the `.env.example` file for specifying environments like `spigot`, `legacyspigot`, `forge-1-18`, and `neoforge-1-21`.
* **Pre-commit Checks**: Add a new section mentioning the pre-commit checks configured in `.github/workflows/pre-commit-check.yaml` and the use of `pre-commit` for code consistency.
* **Release Process**: Add a new section detailing the release process using `release-please` as configured in `.github/workflows/release-please.yml`.
* **Snapshot Builds**: Add a new section providing information about the snapshot builds workflow defined in `.github/workflows/snapshots.yml`.
* **Code Formatting**: Add a new …
> chore: update the readme with a few details

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/commands/subcommands/desti/TeleportDestiSubCommand.java
- core/src/main/java/com/sekwah/advancedportals/core/connector/containers/CommandSenderContainer.java
- core/src/main/java/com/sekwah/advancedportals/core/permissions/Permissions.java
- lang/src/main/resources/lang/en_GB.lang
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotCommandSenderContainer.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/connector/container/SpigotCommandSenderContainer.java
Needs testing but should be good enough for now
> feat: add desti warp player sub command

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/commands/subcommands/desti/RenameDestiCommand.java
- core/src/main/java/com/sekwah/advancedportals/core/permissions/Permissions.java
- core/src/main/java/com/sekwah/advancedportals/core/services/DestinationServices.java
- lang/src/main/resources/lang/en_GB.lang
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/LegacySpigotInfoLogger.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/PermissionsGeneratorSpigot.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/commands/subcommands/portal/ImportPortalSubCommand.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/command/LegacySpigotCommandHandler.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotCommandSenderContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotPlayerContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotServerContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/connector/container/LegacySpigotWorldContainer.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/importer/ConfigAccessor.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/importer/LegacyImporter.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/tags/ConditionsTag.java
- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/warpeffects/EnderWarpEffect.java
resolves #547 
Needs to be tested in-game before pushing.
> feat: add rename destination command

- core/src/main/java/com/sekwah/advancedportals/core/tags/DestiTag.java
> fix: null check for DestiTag

- core/src/main/java/com/sekwah/advancedportals/core/portal/AdvancedPortal.java
> fix: private the injection

- legacyspigot/src/main/java/com/sekwah/advancedportals/legacyspigot/tags/ConditionsTag.java
- spigot/src/main/java/com/sekwah/advancedportals/spigot/tags/ConditionsTag.java
> fix: clean up conditions

- core/src/main/java/com/sekwah/advancedportals/core/AdvancedPortalsCore.java
- core/src/main/java/com/sekwah/advancedportals/core/commands/subcommands/portal/MovePortalSubCommand.java
- lang/src/main/resources/lang/en_GB.lang
~~Requires testing~~ Tested and works
Fixes #313
> feat: add portal move command
